version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: metrics_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aviahack
      POSTGRES_PASSWORD: aviahack8
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
